name: AutoZip

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.1
        with:
          files: arch/
          dest: hyperfluent-arch.tar.gz
